# These are supported funding model platforms

github: # [reygcalantaol]
patreon: # ReyCalantaol
custom: # ['https://www.buymeacoffee.com/reygcalantaol', 'https://paypal.me/reygcalantaol?country.x=PH&locale.x=en_US']
